unmatching_file:
  path: 'Catálogo Abarrotes Carnes y Lácteos 2019-1 (1).xlsx'
  id_col: index
  gtin_col: 'COD BARRAS'
  product_namme_col: 'PRODUCTO'
  kargs:
    skiprows: 6

dump_database:
  retailer:
    - soriana
    - soriana_online
    - chedraui
    - fresko
    - city_market
    - la_comer
    - comercial_mexicana
    - superama
    - waltmart
    - heb
matching_text:
  precision: 0.9
